# Generated by Django 3.1.3 on 2020-11-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20201128_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
    ]
