# Generated by Django 3.1.3 on 2020-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_remove_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='admin', max_length=255, verbose_name='Fast Name'),
        ),
    ]
