# Generated by Django 3.1.3 on 2021-01-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20201129_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Fast Name'),
        ),
    ]
